CREATE TABLE IF NOT EXISTS endpoint_hits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app VARCHAR(255) NOT NULL,
    uri VARCHAR(2048) NOT NULL,
    ip VARCHAR(50) NOT NULL,
    timestamp TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_endpoint_hits_timestamp ON endpoint_hits (timestamp);
CREATE INDEX IF NOT EXISTS idx_endpoint_hits_uri ON endpoint_hits (uri);
CREATE INDEX IF NOT EXISTS idx_endpoint_hits_app_uri ON endpoint_hits (app, uri);
